doc.type html
script
html
head
utf8
viewportcontent=width=device-width,initial-scale=one
title covid strings30 first round bracket
link rel= stylesheet href=css
head
body
bracket-container{}
matchup
solid zero;
filename=covid strings30 first round.js
first round=(highest overall seed ,second highest seed third highest seed, first middle seed, second middle seed, third lowest seed ,second lowest seed, lowest overall seed)
highest overall seed =seed1
second highest seed=seed2
third highest seed=seed3
firstmiddleseed=seed4
second middle seed =seed5
third lowest seed= seed6
second lowest seed =seed7
lowest overall seed =seed8
covid strings team list30=[burgundy,orange,blue,pink,red,purple,violet,black]
matchup1=(violet versus orange)
matchup2=(purple versus blue)
matchup3=(red versus pink)
matchup4=(black versus burgundy)
document.createelement 
matchupdiv.classname=(matchup)
matchupdiv.inner html =[matchup]
rounddiv.appendchild(matchup)
for (i in covid strings first round)
round div=create element
round div class name=covid strings30 first round
bracket.appendchild(round div)
if (event.target.covid strings seed list.contains(matchup))
return matchup
else:
addmatchup
java util.scanner
java.util
questions[]questions={
question1
question2
question3
question4
question5
question6
question7
question8
question9
question10
question11
question12
question13
question14
question15
question16
if selectedanswer==correct:
return true
else:
return false
advancingteam=slice(current teams)
result=declarewinner(matchup1)
if orange score>=forty:
console.log(orange rna messengers win)
else:
console.log(violet relivers win)
result=declarewinner(matchup2)
if blue score>=forty:
console.log(blue curve crushers win)
else:
console.log(purple brave hearts win)
result=declarewinner(matchup3)
if pink score>=forty:
console.log(pink covid disease fighters win)
else:
console.log(red protein spikers win)
result=declarewinner(matchup4)
if burgundy score>=forty:
console.log(burgundy rebuilders win)
else:
console.log(black night riders win)
return filename


