doc.type.html
script
filename=covidstrings30.js
java.awt graphics 
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document get element by id(header)
src.append child(this.img)
div id=header/div>
audio=new audio(audio_file mp3)
audio.play
random button
new button(set random color)
option button
new button(change color)
public fun with graphics(){
color panel=new j panel();
add (panel,center )
button panel
new panel (new flowlayout(flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public action performed(actionevent e)
random r= newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(r nextint(13),(r nextint(13),(r nextint(13),(r nextint(13)))
num teams
total players= players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e){
colorm=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string [] args){
jframe f = new covid strings30()
f.set title(covid strings30)
f.set default close operation(exit_on_close);
f.set size
f.set visible(true);
<label id=lbl score>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object{a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object=[team color]
covid strings team list30=[burgundy rebuilders,orange rna messengers,blue curve crushers,pink covid disease fighters,red protein spikers,purple brave hearts,violet relivers,black night riders]
covid strings phrase list30=[non-concatenated strings
"the idea that covid was the first disease x is possible if were talking in2019 and earlier"
"for example for every case detected 4.8 went undiagnosed"
"even if covid spread earlier its unlikely that large numbers of people would be undiagnosed"
"one new sign of long covid though is increased inflammation"
"one false sign is the idea that sylvia browne predicted covid"
"it is likely to be just a lucky guess"
"the end of days is perhaps just another after the fact attempt to predict covid out of the phrase a severe pneumonia like illness"
"perhaps if kim kardashian cites you your credibility is questionable"
concatenated strings
"the"+"fact"+"that"+"browne"+"also"+"had"+"a"+"similar"+"prediction"+"in"+"2004"+"means"+"its"+"even"+"less"+"likely"+"that"+"shes"+"right"
"just"+"because"+"the"+"1981"+"farmers"+"almanac"+"claimed"+"to"+"predict"+"covid"+"does"+"not"+"mean"+"its"+"foreshadowing"+"either"
"wuhan"+"400"+"is"+"the"+"latest"+"claim"+"of"+"covid"+"prophecies"
"unfortunately"+"there"+"is"+"no"+"eye"+"of"+"darkness"+"surrounding"+"covid"
"there"+"is"+"also"+"no"+"clear"+"heart"+"of"+"darkness"+"either"
"the"+"bigger"+"trend"+"is"+"that"+"there"+"is"+"some"+"power"+"with"+"predictions"+"if"+"nostradamus"+"is"+"cited"+"for"+"predicting"+"covid"
"if"+"countdown"+"to"+"aploycase"+"was"+"devoted"+"to"+"covid"+"it"+"would"+"certainly"+"mention"+"quotes"+"about"+"pneumonia"+"like"+"viruses"+"appearing"+"and"+"disappearing"
"maybe"+"if"+"there"+"is"+"truth"+"to"+"nostradamus"+"covid"+"predictions"+"we"+"should"+"be"+"concerned"+"about"+"the"+"rest"+"of"+"the"+"twenty-first"+"century"]
covid strings multiple choice list30=[1:a 4.8 b 2.5 c 105.9 d 106.1,2:a 1687 b 1789 c 1981 d 2048,3:a 400 b 2019 c 2020 d 3000,4:a the cold play song apocalypse b the100 year anniversary of the spanish flu c apocalypse d the super bowl,5:a sign b negative c positive d idol,6:a rick brights b robert redfields c nostradamus d qanon,7:a y b x c question mark d z,8:a2004 b2005 c2007 d2019,9:a small b large c a bevy d a bakers dozen,10:a clear b extinguisher c black hole like d covid vaccine,11:a increased b decreased c periodic d weathering,12:a weather forecasting b analytics c predictions d sourcing,13:a cryptic cipher b lucky guess c equation d bet,14:a heart b eye c mind d spirit]
covid strings30 math problem list=[ non-concatenated "if a line of detected and undiagnosed covid cases shows that the undiagnosed cases decrease with more detection what is the relationship"?,"if a line involving covid cases and diagnoses has a slope of 4.8 and a y intercept of 2.5 what would the y coordinate be if the x coordinate is 10"?,"if a new x coordinate was placed at 5 what would the new y coordinate be"?,"if the previous point was reflected over the y axis what is the new point"?,"if the previous point was rotated 180 degrees what is the new point"?,"if the previous point was rotated 270 degrees clockwise what is the new point?,if the previous point was translated11 units down and6 units to the left what is the new point"?,"if the new point was translated units6 up and14 units to the right what is the new point"?,
concatenated "if"+"a"+"poll"+"found"+"that"+"57"+"percent"+"of"+"americans"+"are"+"distrustful"+"of"+"silvia"+"browns"+"covid"+"predictions"+"what"+"percent"+"arent"?,"if"+"47"+"percent"+"strongly"+"distrust"+"browne"+"what"+"percent"+"are"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"4.204"+"percent"+"what"+"is"+"the"+"range"?,"if"+"a"+"poll"+"shows"+"that"+"37"+"percent"+"trust"+"the"+"1981"+"farmers"+"almanacs"+"covid"+"prediction"+"what"+"percent"+"dont"?,"if"+"24"+"percent"+"strongly"+"trust"+"the"+"covid"+"prediction"+"what"+"percent"+"are"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"3.63"+"percent"+"what"+"is"+"the"+"range"?]
covid string scrambled phrase list30=["ostrdanm+ovicd+redpictions","oivcd+0912+seida+x"]
userin.select team
import meta.
class myclass
constructor(non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(Concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax
chart js 
def gradient
id=mygradient
gradientunits=userspaceonuse
if functionslope<0:
return inverse relationship
else:
return no relationship
x1=0
y1=2.5
x2=10
y2=x2*4.8+Y1
stop offset=0 stop-color=ff0000
stop offset=1 stop color=0000ff
<lineargradient>
<filter
id=linear1
filterunits=objectboundingbox
x=0%
y=0%
width=100%
height=100%
<fecomponenttransfer>
<fefunccovidstrings type=linear slope>=1
transformationlist=[reflection,rotation,translation]
if reflection (5,26.5)==y axis:
sign.change x coordinate
else:
shift y axis
if rotation(-5,26.5)=180 degrees 
shift 180 degrees
else:
remain
if rotation(5,-26.5)==270 degrees clockwise:
shift 270 degrees clockwise 
else:
remain
if translation==(-6,-11):
shift 6 units to the left and 11 units down
else:
remain
if translation==(14,6):
shift 14 units to the right and 6 units up
else:
remain
substring(start,end)
userin.multiple choice
if (s1.length())!=s2.length: 
return false
if s1.length()==s2.length:
return true
char[]arr1=s1.tochararray
char[]arr2=s2.tochararray
arrays.sort(arr1)
arrays.sort(arr2)
if selectedanswer==correct answer:
return true
else:
return false
if selectedanswer=not correct:
return false
else:
return true
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet) 
if users team wins covid strings30 
console log users team wins covid strings30 
else
return game over
return filename

